// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'boxIMG': string;
  'count': string;
  'countGray': string;
  'countRed': string;
  'food': string;
  'icon': string;
  'itemFood': string;
  'menuDetails': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
