// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'boxItem': string;
  'container': string;
  'imgMenu': string;
  'itemFood': string;
  'items': string;
  'title': string;
  'topMenu': string;
  'viewMore': string;
}
export const cssExports: CssExports;
export default cssExports;
