// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottomFixed': string;
  'boxBottom': string;
  'boxButton': string;
  'button': string;
  'card': string;
  'cards': string;
  'choose': string;
  'chooses': string;
  'contents': string;
  'count': string;
  'discount': string;
  'into': string;
  'item': string;
  'money': string;
  'payment': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
