// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottom': string;
  'btn-group': string;
  'google': string;
  'icon': string;
  'iconSearch': string;
  'input-field': string;
  'input-icons': string;
  'search': string;
  'text-center': string;
}
export const cssExports: CssExports;
export default cssExports;
