// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'category': string;
  'content': string;
  'count': string;
  'icon': string;
  'icon-star': string;
  'img': string;
  'info': string;
  'item': string;
  'items': string;
  'p': string;
  'span': string;
  'text': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
