// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'choose': string;
  'chooses': string;
  'contents': string;
  'infor': string;
  'item': string;
}
export const cssExports: CssExports;
export default cssExports;
