// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'address': string;
  'checkIn': string;
  'col': string;
  'detail': string;
  'fontSize': string;
  'input-field': string;
  'message': string;
  'note': string;
  'search': string;
  'time': string;
}
export const cssExports: CssExports;
export default cssExports;
