// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'boxItem': string;
  'container': string;
  'food': string;
  'loading': string;
}
export const cssExports: CssExports;
export default cssExports;
