// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'boxSwiper': string;
  'container': string;
  'header': string;
  'imgListItem': string;
  'itemParent': string;
  'shadow': string;
  'slider': string;
  'textDescription': string;
  'textRed': string;
}
export const cssExports: CssExports;
export default cssExports;
