// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottomFixed': string;
  'boxButton': string;
  'button': string;
  'card': string;
  'cards': string;
  'description': string;
  'discount': string;
  'point': string;
}
export const cssExports: CssExports;
export default cssExports;
