// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottomFixed': string;
  'boxButton': string;
  'button': string;
  'gmap_canvas': string;
  'input-field': string;
  'mapouter': string;
  'search': string;
}
export const cssExports: CssExports;
export default cssExports;
