// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'amount': string;
  'boxBottom': string;
  'contents': string;
  'count': string;
  'into': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
