// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'cost': string;
  'count': string;
  'description': string;
  'sale': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
