// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottomFixed': string;
  'boxButton': string;
  'boxChoose': string;
  'button': string;
  'information': string;
  'inputType': string;
  'sort': string;
  'special': string;
}
export const cssExports: CssExports;
export default cssExports;
