// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'boxSwiper': string;
  'btn-danger': string;
  'btn-default': string;
  'group': string;
}
export const cssExports: CssExports;
export default cssExports;
