// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'inputOtp': string;
  'otp-field': string;
  'resend': string;
  'row': string;
  'text-center': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
