// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'iconSearch': string;
  'imgIconKing': string;
  'imgIconMomo': string;
  'input-field': string;
  'item': string;
  'search': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
